### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by bpisano**
The actual app icon was designed for the Yosemite styled macOS. But now, it look a bit outdated. I took the time to design a set of icons that matches the new style of macOS.

The first one is the more neutral and soft of all. This is probably the one that most of you will like as it is very clean.

macOS

But I authorized myself to go a bit crazier and designed other icons that would be more funny. Here are some eyes with different backgrounds.

macOS 3
macOS 2
macOS

I also tried some iterations with glasses.

macOS 2
macOS

And finally, I went a bit crazy with this one. Based on the big eye, I designed a little creature with a big eye. This little monster might probably be too funny for this kind of project. But I wanted to share the most of my iterations so you can consider them.

macOS 2
macOS
macOS 3

In the Xcode project, the icon is already set with the first one. Let me know what you think.

### CODE REVIEW

**Comment by chamburr** [comment]
@bpisano Thank you for taking time to create these icons - they look awesome! At first glance, I like the eye icon with dark background the most. Let me think about which icon to choose. If anyone has different opinions please share it here

**Comment by bpisano** [comment]
Thanks ! The choice is completely yours. I can also make adjustments to some icons if needed.

**Comment by chamburr** [comment]
Hi @bpisano, sorry for the late reply. I think the eye icon with the dark background is the best. Let’s use that one! 🎉

**Comment by bpisano** [comment]
Done. I've replaced the old icon with the one with an eye and a dark background.

**Review by chamburr — APPROVED** [review]

**Pull request merged**
